/**
 * Elenco tracce in public/meditation-playlist/
 * Rigenera: node scripts/sync-guided-meditation-tracks.mjs
 */
export const GUIDED_MEDITATION_TRACK_FILENAMES: string[] = [
  "Adrien Magnusen - Astronaut Scent.mp3",
  "Aerial Lakes - Dewdrops.mp3",
  "Aitne - Caldera.mp3",
  "Aitne - Mechanics.mp3",
  "Alfa Cognitive - Eris Orbit.mp3",
  "Alma Tranquilo - Autumn Serenity.mp3",
  "Alón Celestia - Solice.mp3",
  "Alsephina - Caligo.mp3",
  "Altered Source - A Concurrence of Circumstances.mp3",
  "Ambienne - Weightless Horizon.mp3",
  "Ambient Eternal - Unfolding Into Night.mp3",
  "Åmliden - Distant Orbit.mp3",
  "Amos Stremann - Signal to silence.mp3",
  "Antologie - Ode to the Sky.mp3",
  "Apollo Vision - Unfolding.mp3",
  "Arlo Leclerc - Fulfilment.mp3",
  "Arush Mandal - Source.mp3",
  "Astra Sky - From Another Spectra.mp3",
  "Astral Explorer - Ethereal Horizon.mp3",
  "Astral Tides - Amberine.mp3",
  "AstroAether - minimal.mp3",
  "Aurora Aeterna - Angel of Sleep.mp3",
  "Avvaken - Blooming.mp3",
  "Awake or Asleep - Combination.mp3",
  "Ayala Cola - Kontur.mp3",
  "Ayivah - Eternal Light.mp3",
  "Bayesian - Tandem.mp3",
  "Bedtime Muse - rivers.mp3",
  "Blauberg Calm - Slow Files.mp3",
  "Blossom Inn - Into the aether.mp3",
  "cairn - Mystic Ocean Whispers.mp3",
  "Calm Lecce - Enter Eternity.mp3",
  "Calmative - Ethereal Balance.mp3",
  "Calmative - Soft Touch.mp3",
  "Calming Eyes - Wellbeing.mp3",
  "CasaLuna - Evening Calm.mp3",
  "Catedral Infinita - Desiderium.mp3",
  "Cristoforo Giordano - Recreational.mp3",
  "Deep Dive Meadow - Passion for You.mp3",
  "different spaces - Already.mp3",
  "Digitalis - Neural Cloud.mp3",
  "Divine Vibration - Deep Journeys.mp3",
  "Divine Vibration - Lunar Drift.mp3",
  "Doosi - Silhouette.mp3",
  "Dopamine clouds - Oniria.mp3",
  "Dreamstate - Neptune.mp3",
  "Dronia - Yearning.mp3",
  "Dunsø - Klippa.mp3",
  "Ebon Meadow - Tender Air.mp3",
  "Echoes of the Past - Sliding Doors.mp3",
  "Eldrelder - Slumbering City.mp3",
  "Elias Mía - Ecliptica.mp3",
  "Eline Moss - Narvik.mp3",
  "Elunara Mare - Sun Child.mp3",
  "Elunara Mare - Valerian.mp3",
  "Ember Rivera - Melodia Lunae.mp3",
  "Emberlace - Presence of Mind.mp3",
  "Embertone - Cosmosis.mp3",
  "ẹmi - Whispered Grove.mp3",
  "Eternalistic - Among the Fireflies.mp3",
  "Eternalistic - Luminous Fragments.mp3",
  "Ethereal Nexus - Ulthae.mp3",
  "Ethereva - Place of Peace (ambient sleep).mp3",
  "Etherielle - Lingering Dream.mp3",
  "Evanesce - Driftwood Memory.mp3",
  "Evanesce - Halcyon Lull.mp3",
  "Evanesce - Moonlit.mp3",
  "Evensia - Dreaming.mp3",
  "Ex Nocte - Etereo.mp3",
  "Felix Lancaster - Breath of the Wildflower.mp3",
  "Foora - From near to far.mp3",
  "Frail Horizon - Tideveil.mp3",
  "Fred Russ - blacklight veil.mp3",
  "Gallway Flex - Glowfall.mp3",
  "Gordo Napalma - Dancing Particles.mp3",
  "Hank Sky - Allure.mp3",
  "Hank Sky - Floating Calm.mp3",
  "Hanna Lindgren - Sense of Relief.mp3",
  "Har Rhei - Landscape.mp3",
  "Harmonic Reverie - Golden Silence.mp3",
  "Hazel Day - Dream in red.mp3",
  "Horizon Mind - Iridescent.mp3",
  "Insomnian - Ethereal Reverie.mp3",
  "Institute of Noise - Lithosphere.mp3",
  "Isolune - Omega.mp3",
  "ispíritu - Doranel.mp3",
  "ispíritu - Halycon.mp3",
  "Jack Allenson - Terracotta.mp3",
  "Johann Eder - Forgiveness.mp3",
  "Joseph Vidal - Segno.mp3",
  "Kai Monroe - Zephyr.mp3",
  "Kal Koren - Red Canna.mp3",
  "Koma - Downtime.mp3",
  "Kuyenao - Blooming Echoes.mp3",
  "La Luce - Celestial Glowing.mp3",
  "Lake Melville - Lumineth.mp3",
  "Lasant - A Brief Disappearance.mp3",
  "Lasant - Prepere for Landing.mp3",
  "Laurent Emmmerling - Unity.mp3",
  "Laurent Leflaive - Lucent Veil.mp3",
  "Lejo - Torpet.mp3",
  "Les Coralines - Entier.mp3",
  "Ljusnan - Frid.mp3",
  "Ljusnan - Seloria.mp3",
  "Ljusnan - Softly.mp3",
  "Lueen - Leap of Faith.mp3",
  "Lumen Sonitus - Harvest.mp3",
  "Luminary Night - Inward.mp3",
  "Lux Alba - Whispering Light (Meditation).mp3",
  "Lynx XII - Ascended Master.mp3",
  "Lynx XII - at the moment.mp3",
  "Lynx XII - Orbital Eccentricity.mp3",
  "Månvarv - Attentive.mp3",
  "Marble Sky - Solace Flow.mp3",
  "Matsyendrasana - Under Wet Leaves.mp3",
  "Matt Deep - Fragments.mp3",
  "Max Moller - Calendulum.mp3",
  "Mindful Meadow - Phorosine.mp3",
  "Molnen - Velvet Dusk.mp3",
  "Monte Aria - Breathe.mp3",
  "Moonhollow - Afterlight Currents.mp3",
  "Moonlace - Enthral.mp3",
  "Moonlace - Halo Phenomenon.mp3",
  "Moonweaver - Somnolent.mp3",
  "Morgondimma - Quietude.mp3",
  "Najia - Effortless Elevation.mp3",
  "Nathaniel Rembrandt - Night Sky.mp3",
  "Nebuu - Emotional Release.mp3",
  "New Lab - Fermion.mp3",
  "Nimara - Breathtone.mp3",
  "Nimara - Nightflora.mp3",
  "Noah Moon - Phonics.mp3",
  "Noah Moon - Quantum.mp3",
  "Noctivelle - Infinite Escapes.mp3",
  "Nocturna Blooms - Floating Away.mp3",
  "Noor Alston - Positive Thinking.mp3",
  "Novera Rae - Awareness.mp3",
  "Nubilum Vespera - Sanitatem.mp3",
  "Oblivion - Shadows of Winter.mp3",
  "Oblivionis - Echoes of the Night.mp3",
  "Ögonblick - Lynx.mp3",
  "OmniBrain - The Bloom Within.mp3",
  "Opheralis - Deep Connection.mp3",
  "Orchestrate the Universe - Light.mp3",
  "Peyote Level - Dawnveil.mp3",
  "Photoautotroph - Fulfillment.mp3",
  "Phylloscopus humei - Unakite.mp3",
  "pkwy. - Autumn Winds.mp3",
  "Priy - Vibe.mp3",
  "Quantum Veil - Crystal Halos.mp3",
  "Revivo Wide - A Quiet Distance.mp3",
  "Revivo Wide - Aetheron.mp3",
  "Revivo Wide - Conundrum.mp3",
  "S Dedalus - Lores.mp3",
  "Sable Flo - Beyond Mist.mp3",
  "Sable Flo - Himmelaku.mp3",
  "Sadeus - duskfall.mp3",
  "Safe Mode - Soft Blur.mp3",
  "Sasha Coleman - Glass Moons, Quiet Orbits.mp3",
  "Sassani - Tao Flow.mp3",
  "Seraphine - Mountain.mp3",
  "Seth Sands - Infinite Ascent.mp3",
  "Shizuka Woods - Deferred.mp3",
  "Silentro - Jasmine.mp3",
  "SKEN - Astray.mp3",
  "Sleepwear - Seamless.mp3",
  "Slow Journey - Aeon.mp3",
  "Solfjord - Noctis.mp3",
  "Somnia Flow - Lunawood.mp3",
  "Somnifera - Sleep Tides.mp3",
  "Sonic Waterfall - Corteza.mp3",
  "Sonic Waterfall - Rhyolite.mp3",
  "Sono Aetheris - Amittere.mp3",
  "spaceboy - celestial warmth.mp3",
  "Stellar Serenity - Evening.mp3",
  "The Endity - Meaningful Existence.mp3",
  "The Inner Room - Serene.mp3",
  "The Nightgate - The Burning Sky.mp3",
  "The Stillframe - Interval.mp3",
  "Theodore Brim - Moments.mp3",
  "Through Quiet Tides - Silver Raindrops.mp3",
  "Torun Lysander - Soothing Triangles.mp3",
  "Tristan Axvall - Fading.mp3",
  "Tundra Miles - Sky Adrift.mp3",
  "Universal Embrace - Droplets.mp3",
  "Universal Embrace - Echoes.mp3",
  "unvrsl frqncy - Entanglement.mp3",
  "Unwritten Skies - Benevolent.mp3",
  "Ursae Minoris - Samudaya.mp3",
  "Vau Dio - Depth.mp3",
  "Ventura Lumi - Atmosphere.mp3",
  "Visual Flow - Slö.mp3",
  "Volta Celeste - Toccante.mp3",
  "Wandercole - CASOS.mp3",
  "Warmth of Muba - Eclipse of Silence.mp3",
  "William Edessa - Lights.mp3",
  "Zephyrical - Between Minds.mp3",
]
